name: Patch Testing for Kernel
on:
    workflow_dispatch:

env:
    PKGDEST: "/tmp/linux-hybrid"

jobs:
    build-kernel:
      env:
        _build_cpu_opt: "generic"

      runs-on: ubuntu-latest
      container: archlinux:base-devel

      steps:

          - name: Install Deps
            run: pacman -Syu --noconfirm git

          - name: Clone kernel PKGBUILD
            run: |
              git clone https://gitlab.com/hybrid-project-developers/pkgbuilds/hybrid-core-pkgbuilds/kernel/linux-hybrid.git
              cd linux-hybrid

          - name: Prepare for makepkg
            run: |
              pacman -Syu --noconfirm sudo
              useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
              chown user -R ..
              chown user -R /tmp

          - name: Compile
            run: | 
              cd /__w/linux-hybrid-patch-testing/linux-hybrid-patch-testing/linux-hybrid
              su user -c "yes '' | makepkg --noconfirm -s"
          
          - uses: actions/upload-artifact@v3
            with:
              name: kernel-packages-${{ env._build_cpu_opt }}
              path: ${{ env.PKGDEST }}/linux*.pkg.tar.zst

    build-kernel-v2:
      env:
        _build_cpu_opt: "generic_v2"

      runs-on: ubuntu-latest
      container: archlinux:base-devel

      steps:

          - name: Install Deps
            run: pacman -Syu --noconfirm git

          - name: Clone kernel PKGBUILD
            run: |
              git clone https://gitlab.com/hybrid-project-developers/pkgbuilds/hybrid-core-pkgbuilds/kernel/linux-hybrid.git
              cd linux-hybrid

          - name: Prepare for makepkg
            run: |
              pacman -Syu --noconfirm sudo
              useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
              chown user -R ..
              chown user -R /tmp

          - name: Compile
            run: | 
              cd /__w/linux-hybrid-patch-testing/linux-hybrid-patch-testing/linux-hybrid
              su user -c "yes '' | makepkg --noconfirm -s"
          
          - uses: actions/upload-artifact@v3
            with:
              name: kernel-packages-${{ env._build_cpu_opt }}
              path: ${{ env.PKGDEST }}/linux*.pkg.tar.zst

    build-kernel-v3:
      env:
        _build_cpu_opt: "generic_v3"

      runs-on: ubuntu-latest
      container: archlinux:base-devel

      steps:

          - name: Install Deps
            run: pacman -Syu --noconfirm git

          - name: Clone kernel PKGBUILD
            run: |
              git clone https://gitlab.com/hybrid-project-developers/pkgbuilds/hybrid-core-pkgbuilds/kernel/linux-hybrid.git
              cd linux-hybrid

          - name: Prepare for makepkg
            run: |
              pacman -Syu --noconfirm sudo
              useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
              chown user -R ..
              chown user -R /tmp

          - name: Compile
            run: | 
              cd /__w/linux-hybrid-patch-testing/linux-hybrid-patch-testing/linux-hybrid
              su user -c "yes '' | makepkg --noconfirm -s"
          
          - uses: actions/upload-artifact@v3
            with:
              name: kernel-packages-${{ env._build_cpu_opt }}
              path: ${{ env.PKGDEST }}/linux*.pkg.tar.zst
